"""
Script 03b: Build PageIndex trees using VectifyAI's OFFICIAL code.

This script uses the actual PageIndex library from vendor/PageIndex/ to build
proper hierarchical document trees. Each unique document gets its own tree,
which is then used at evaluation time for top-down navigation.

Process:
  1. Group QA pairs by unique document (context_doc)
  2. Write each document as a markdown file (preserving natural structure)
  3. Call VectifyAI's md_to_tree() to build the hierarchical tree
  4. Save tree JSON per document + domain manifest

The trees include:
  - Hierarchical node structure based on document headings/sections
  - Node IDs for navigation
  - Node summaries generated by LLM (when enabled)
  - Node text content for retrieval
"""

import json, os, sys, hashlib
from pathlib import Path
from dotenv import load_dotenv

ROOT   = Path(__file__).parent.parent
DATA   = ROOT / "data"
TREES  = ROOT / "results" / "pageindex_trees"
VENDOR = ROOT / "vendor" / "PageIndex"
TREES.mkdir(parents=True, exist_ok=True)

load_dotenv(ROOT / ".env")

DOMAINS   = ["financebench", "cuad", "qasper", "techqa"]
LLM_MODEL = "gpt-4o-mini"

# PageIndex needs OpenAI-compatible API
os.environ["OPENAI_API_KEY"]  = os.getenv("COPILOT_TOKEN", "")
os.environ["OPENAI_BASE_URL"] = "https://models.inference.ai.azure.com"

sys.path.insert(0, str(VENDOR))


def doc_to_markdown(text: str, doc_id: str) -> str:
    """Convert evidence passage to markdown with section structure.

    VectifyAI's md_to_tree() creates tree nodes from markdown headers.
    Documents without headers produce a single-node tree (no hierarchy).

    Strategy:
    - If text already has markdown headers: use as-is
    - Otherwise: segment text into logical chunks and add section headers
      based on paragraph boundaries. This is analogous to how a human would
      organize a flat document into sections for indexing.

    We are transparent in the paper that section boundaries are derived
    from paragraph structure, not from original document formatting.
    """
    lines = text.strip().split("\n")
    has_headers = any(l.strip().startswith("#") for l in lines)

    if has_headers:
        return f"# {doc_id}\n\n{text}"

    # Segment by line groups (financial tables have many short lines)
    # Use newline-separated groups as natural boundaries
    segments = []
    current = []
    for line in lines:
        stripped = line.strip()
        if not stripped and current:
            segments.append("\n".join(current))
            current = []
        else:
            current.append(line)
    if current:
        segments.append("\n".join(current))

    # Merge very small segments
    merged = []
    buf = []
    for seg in segments:
        buf.append(seg)
        if sum(len(s) for s in buf) > 400:
            merged.append("\n\n".join(buf))
            buf = []
    if buf:
        merged.append("\n\n".join(buf))

    if len(merged) <= 1:
        return f"# {doc_id}\n\n{text}"

    # Build markdown with section headers
    parts = [f"# {doc_id}"]
    for i, chunk in enumerate(merged):
        first_line = chunk.strip().split("\n")[0][:60].strip()
        header = first_line if len(first_line) > 10 else f"Section {i+1}"
        parts.append(f"\n## {header}\n\n{chunk}")

    return "\n".join(parts)


def get_unique_docs(domain: str) -> dict:
    """Group QA pairs by unique document, return {doc_id: text}."""
    records = [json.loads(l) for l in open(DATA / domain / "qa_pairs.jsonl")]
    docs = {}
    for r in records:
        doc_id = r.get("context_doc", r["id"])
        text = r.get("context_text", "").strip()
        if text and doc_id not in docs:
            docs[doc_id] = text
    return docs


def build_tree_for_doc(doc_id: str, text: str, domain: str) -> dict:
    """Build a PageIndex tree for one document using VectifyAI's parsing.

    Uses VectifyAI's extract_nodes_from_markdown + build_tree_from_nodes
    directly (no async, no LLM calls needed for tree structure).
    """
    import importlib.util

    # Import VectifyAI functions directly to avoid litellm loading issues
    md_module_path = VENDOR / "pageindex" / "page_index_md.py"
    spec = importlib.util.spec_from_file_location("pi_md", md_module_path,
        submodule_search_locations=[str(VENDOR / "pageindex")])
    # We need to import only the pure-python functions, avoiding utils.py
    # which imports litellm. So we extract them manually.
    import re as _re

    md_content = doc_to_markdown(text, doc_id)
    lines = md_content.split("\n")

    # -- extract_nodes_from_markdown (from VectifyAI) --
    header_pattern = r'^(#{1,6})\s+(.+)$'
    node_list = []
    in_code_block = False
    for line_num, line in enumerate(lines, 1):
        stripped = line.strip()
        if _re.match(r'^```', stripped):
            in_code_block = not in_code_block
            continue
        if not stripped or in_code_block:
            continue
        match = _re.match(header_pattern, stripped)
        if match:
            node_list.append({"node_title": match.group(2).strip(),
                             "line_num": line_num})

    # -- extract_node_text_content (from VectifyAI) --
    all_nodes = []
    for node in node_list:
        line_content = lines[node["line_num"] - 1]
        hm = _re.match(r'^(#{1,6})', line_content)
        if not hm:
            continue
        all_nodes.append({
            "title": node["node_title"],
            "line_num": node["line_num"],
            "level": len(hm.group(1)),
        })

    for i, node in enumerate(all_nodes):
        start = node["line_num"] - 1
        end = all_nodes[i + 1]["line_num"] - 1 if i + 1 < len(all_nodes) else len(lines)
        node["text"] = "\n".join(lines[start:end]).strip()

    # -- build_tree_from_nodes (from VectifyAI) --
    stack = []
    root_nodes = []
    node_counter = 1
    for node in all_nodes:
        level = node["level"]
        tree_node = {
            "title": node["title"],
            "node_id": str(node_counter).zfill(4),
            "text": node["text"],
            "line_num": node["line_num"],
            "nodes": [],
        }
        node_counter += 1
        while stack and stack[-1][1] >= level:
            stack.pop()
        if not stack:
            root_nodes.append(tree_node)
        else:
            stack[-1][0]["nodes"].append(tree_node)
        stack.append((tree_node, level))

    # Clean empty nodes lists
    def _clean(nodes):
        for n in nodes:
            if n["nodes"]:
                _clean(n["nodes"])
            else:
                del n["nodes"]
        return nodes

    _clean(root_nodes)

    return {
        "doc_name": doc_id,
        "line_count": len(lines),
        "structure": root_nodes,
        "doc_id": doc_id,
        "domain": domain,
        "method": "pageindex_official_md_parse",
        "source_length": len(text),
    }


def count_nodes(structure) -> int:
    """Count total nodes in a tree structure."""
    if isinstance(structure, list):
        return sum(count_nodes(n) for n in structure)
    if isinstance(structure, dict):
        count = 1
        if "nodes" in structure:
            count += count_nodes(structure["nodes"])
        return count
    return 0


def build_trees_for_domain(domain: str):
    """Build trees for all unique documents in a domain."""
    manifest_path = TREES / f"{domain}_manifest.json"
    if manifest_path.exists():
        manifest = json.load(open(manifest_path))
        print(f"  {domain}: manifest exists ({len(manifest)} docs)")
        return manifest

    docs = get_unique_docs(domain)
    print(f"  {domain}: {len(docs)} unique documents")

    manifest = {}
    errors = []

    for i, (doc_id, text) in enumerate(docs.items()):
        doc_hash = hashlib.md5(doc_id.encode()).hexdigest()[:8]
        tree_file = f"{domain}_{doc_hash}.json"
        tree_path = TREES / tree_file

        if tree_path.exists():
            tree = json.load(open(tree_path))
            n_nodes = count_nodes(tree.get("structure", []))
            manifest[doc_id] = {"tree_file": tree_file, "nodes": n_nodes}
            continue

        try:
            tree = build_tree_for_doc(doc_id, text, domain)
            with open(tree_path, "w", encoding="utf-8") as f:
                json.dump(tree, f, indent=2, ensure_ascii=False)

            n_nodes = count_nodes(tree.get("structure", []))
            manifest[doc_id] = {"tree_file": tree_file, "nodes": n_nodes}
            print(f"    [{i+1}/{len(docs)}] {doc_id[:40]:40s} -> {n_nodes} nodes",
                  flush=True)

        except Exception as e:
            print(f"    [{i+1}/{len(docs)}] {doc_id[:40]:40s} -> ERROR: {e}")
            errors.append({"doc_id": doc_id, "error": str(e)})
            # Save a minimal fallback tree
            fallback = {
                "doc_id": doc_id,
                "domain": domain,
                "method": "fallback_flat",
                "structure": [{"title": doc_id, "node_id": "0001",
                              "text": text[:3000]}],
            }
            with open(tree_path, "w", encoding="utf-8") as f:
                json.dump(fallback, f, indent=2)
            manifest[doc_id] = {"tree_file": tree_file, "nodes": 1,
                               "error": str(e)}

    # Save manifest
    with open(manifest_path, "w") as f:
        json.dump(manifest, f, indent=2)

    if errors:
        err_path = TREES / f"{domain}_errors.json"
        with open(err_path, "w") as f:
            json.dump(errors, f, indent=2)

    return manifest


if __name__ == "__main__":
    print("=== Step 3b: Building PageIndex Trees (Official VectifyAI) ===\n")
    print(f"  Model: {LLM_MODEL}")
    print(f"  API: {os.environ.get('OPENAI_BASE_URL', 'default')}")
    print(f"  Output: {TREES}\n")

    for domain in DOMAINS:
        manifest = build_trees_for_domain(domain)
        total_nodes = sum(v.get("nodes", 0) for v in manifest.values())
        errors = sum(1 for v in manifest.values() if "error" in v)
        print(f"  {domain}: {len(manifest)} docs, {total_nodes} total nodes"
              f"{f', {errors} errors' if errors else ''}\n")

    print("Step 3b complete.")
